// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Infrastructure.Data;

#nullable disable

namespace OrderService.API.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20240603084516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("OrderService.Core.Entities.EquipmentModel", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderModelOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("EquipmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrderModelOrderId");

                    b.ToTable("EquipmentModel");
                });

            modelBuilder.Entity("OrderService.Core.Entities.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("OrderModels");
                });

            modelBuilder.Entity("OrderService.Core.Entities.EquipmentModel", b =>
                {
                    b.HasOne("OrderService.Core.Entities.OrderModel", null)
                        .WithMany("EquipmentList")
                        .HasForeignKey("OrderModelOrderId");
                });

            modelBuilder.Entity("OrderService.Core.Entities.OrderModel", b =>
                {
                    b.Navigation("EquipmentList");
                });
#pragma warning restore 612, 618
        }
    }
}
