// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderService.Infrastructure.Data;

#nullable disable

namespace OrderService.API.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("OrderService.Core.Entities.EquipmentInOrderModel", b =>
                {
                    b.Property<int>("EquipmentInOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderModelOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EquipmentInOrder");

                    b.HasIndex("OrderModelOrderId");

                    b.ToTable("EquipmentInOrderModel");
                });

            modelBuilder.Entity("OrderService.Core.Entities.OrderModel", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("OrderModels");
                });

            modelBuilder.Entity("OrderService.Core.Entities.EquipmentInOrderModel", b =>
                {
                    b.HasOne("OrderService.Core.Entities.OrderModel", null)
                        .WithMany("EquipmentList")
                        .HasForeignKey("OrderModelOrderId");
                });

            modelBuilder.Entity("OrderService.Core.Entities.OrderModel", b =>
                {
                    b.Navigation("EquipmentList");
                });
#pragma warning restore 612, 618
        }
    }
}
